# conditional CIFAR10 generation with SN and projection discriminator
iteration: 50000

models:
  generator:
    fn: nets/resnet.py
    name: ResnetGenerator32
    args:
      z_dim: 128
      bottom_width: 4
      ch: 256
      n_categories: 10


  discriminator:
      fn: nets/resnet.py
      name: ResnetDiscriminator32
      args:
        ch: 128
        n_categories: 10
        spectral_norm: 1

dataset:
  fn: datasets/cifar10.py
  name: Cifar10
  args:
    train: True
    shuffle: True
    pin_memory: True
    drop_last: True

optimizer:
  name: adam
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

trainer:
  fn: training/trainer.py
  name: GanTrainer
  args:
    n_dis: 5
    n_gen_samples: 64
    loss_type: hinge
    display_interval: 100
    snapshot_interval: 10000
    evaluation_interval: 5000


evaluator:
  fn: training/evaluator.py
  name: Inception
  args:
    n_images: 5000
    batch_size: 100
    splits: 1
