iteration: 250000
seed: 0

models:
  generator:
    fn: nets/resnet.py
    name: ResnetGenerator
    args:
      z_dim: 128
      bottom_width: 4
      ch: 64
      n_categories: 120


  discriminator:
      fn: nets/resnet.py
      name: ResnetDiscriminator
      args:
        ch: 64
        n_categories: 120
        spectral_norm: 1

dataset:
  fn: datasets/imagenet_dog.py
  name: ImageNetDogDataset
  args:
    size: 128
    augmentation: True
    shuffle: True
    pin_memory: True
    drop_last: True

optimizer:
  name: adam
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

scheduler:
  fn: training/scheduler.py
  name: LinearDecayLR
  args:
    decay_start: 250000
    max_iterations: 200000

trainer:
  fn: training/trainer.py
  name: GanTrainer
  args:
    n_dis: 5
    n_gen_samples: 32
    loss_type: hinge
    display_interval: 100
    snapshot_interval: 1000
    evaluation_interval: 5000

evaluator:
  fn: training/evaluator.py
  name: Inception
  args:
    n_images: 50000
    batch_size: 100
    split: 10
