iteration: 250000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 1000
evaluation_interval: 5000

models:
  generator:
    fn: nets/resnet.py
    name: ResnetGenerator
    args:
      z_dim: 128
      bottom_width: 4
      ch: 64
      n_categories: 10


  discriminator:
      fn: nets/resnet.py
      name: ResnetDiscriminator
      args:
        ch: 64
        n_categories: 10
        spectral_norm: 1

dataset:
  fn: datasets/stl10.py
  name: Stl10
  args:
    size: 128
    augmentation: True
    shuffle: True
    pin_memory: True
    drop_last: True

optimizer:
  name: adam
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

scheduler:
  fn: training/scheduler.py
  name: LinearDecayLR
  args:
    decay_start: 250000
    max_iterations: 200000

updater:
  fn: training/updater.py
  name: GanUpdater
  args:
    n_dis: 5
    n_gen_samples: 32
    loss_type: hinge