iteration: 450000
iteration_decay_start: 400000
seed: 0
display_interval: 100
progressbar_interval: 100
snapshot_interval: 1000
evaluation_interval: 5000

models:
  generator:
    fn: nets/resnet.py
    name: ResnetGenerator
    args:
      z_dim: 128
      bottom_width: 4
      ch: 64
      n_categories: 120


  discriminator:
      fn: nets/resnet.py
      name: ResnetDiscriminator
      args:
        ch: 64
        n_categories: 120
        spectral_norm: True

dataset:
  dataset_fn: datasets/imagenet_dog.py
  dataset_name: ImageNetDogDataset
  args:
    shuffle: True
    pin_memory: True
    drop_last: True

optimizer:
  name: adam
  alpha: 0.0002
  beta1: 0.0
  beta2: 0.9

updater:
  fn: training/updater.py
  name: GanUpdater
  args:
    n_dis: 5
    n_gen_samples: 32
    loss_type: hinge
    decay_gamma: 0.999
